### ISSUE TITLE
Pas très SEO freindly :(

### ISSUE THREAD

**Issue by nico-develop** [Lili-Lepage/livret-blanc#11]
https://github.com/Lili-Lepage/livret-blanc/blob/d5f0ee6de402ea5758dc8868a110e6b0da59040c/views/register.html#L9

Comment je fais la promo de cette page sur les réseaux sociaux ?

**Comment by lainesonny** [comment]
Nous avons modifier le title.
Nous n'avons pas encore pensé à cette fonctionnalité.
Nous allons l'envisager dans une version ultérieur.
